services:
  backend: &backend
    command: >
      bash -c "uvicorn main:app --host 0.0.0.0"
    ports:
      - "8000:8000"
    volumes:
      - "./backend/app/db.sqlite3:/app/db.sqlite3"
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: "redis"
      REDIS_DB: 0
    env_file:
      - "./backend/app/.env"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000/api/v1/ping"]
      start_period: 5s
      timeout: 10s
      interval: 5s
      retries: 5
  redis:
    image: redis:7.4.2-alpine
    restart: always
